version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:21.6.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run tests
          command: npm run test

      - run:
          name: Run coverage
          command: npm run test:ci

      - run:
          name: create badge
          command: npx update-badge 

workflows:
  version: 2
  test:
    jobs:
      - test
