version: 2.1
orbs:
  node: circleci/node@5.1.0
  coveralls: coveralls/coveralls@2.2.1

jobs:
  test:
    docker:
      - image: cimg/node:21.6.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Coveralls version 3.1.1
          command: npm install coveralls@3.1.1
      - run:
          name: Run coverage
          command: npm run test:ci
      - run:
          name: Upload coverage to Coveralls with command
          command: chmod +x upload-coveralls.sh
      - run:
          name: Upload coverage to Coveralls
          command: npx coveralls < coverage/lcov.info

workflows:
  version: 2
  test:
    jobs:
      - test
