# version: 2.1

# workflows:
#   test-deploy:
#     jobs:
#       - test
# jobs:
#   test:
#     docker:
#       - image: cimg/node:21.6.2
#     steps:
#       - checkout
#       - run: node --version

version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:21.6.2
    steps:
      - checkout
      - run: node --version
